name: Docker Build

on:
  push:
    branches:
      - '**'  # Triggers on push to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        id: build
        run: |
          set +e  # Disable exit on error
          docker build -t dag_evaluator_image .  # Attempt to build the Docker image
          build_status=$?  # Capture the exit status
          echo "Build status: $build_status"  # Echo the build status for debugging
          set -e  # Re-enable exit on error
          if [ $build_status -ne 0 ]; then
            echo "Docker build failed. Proceeding to rollback."  # Log the failure
            echo "failure" > result.txt
          else
            echo "Docker build succeeded."

            if ! docker run --rm dag_evaluator_image; then
              echo "Docker run failed. Preparing to rollback."
              echo "failure" > result.txt
            else
              echo "Docker run succeeded."
              echo "success" > result.txt
            fi
          fi
      
      - name: Determine result
        id: result
        run: |
          result=$(cat result.txt)
          echo "result=$result" >> $GITHUB_ENV

      - name: Push Docker image (optional)
        if: env.result == 'success'  # Only run if the run step succeeded
        run: |
          docker tag dag_evaluator_image theraddani/dag_evaluator:latest
          docker push theraddani/dag_evaluator:latest

      - name: Rollback if build fails
        if: steps.build.outputs.result == 'failure'  # Only run if the build step failed
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "Rolling back to the last successful commit..."
          # Check if there are previous commits
          if [ $(git rev-list --count HEAD) -gt 1 ]; then
            git config --global user.name "GitHub Actions"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git checkout HEAD^  # This checks out the previous commit
            git push -f https://${GITHUB_TOKEN}@github.com/TheRadDani/dag-mathematical-operations.git HEAD:main  # Replace 'main' with your branch name
          else
            echo "No previous commits to roll back to."
          fi