name: Docker Build

on:
  push:
    branches:
      - '**'  # Triggers on push to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t dag_evaluator_image .
        continue-on-error: false  # Ensure the build fails if there's an error

      - name: Push Docker image (optional)
        if: success()  # Only run if the previous step succeeded
        run: |
          docker tag dag_evaluator_image theraddani/dag_evaluator:latest
          docker push theraddani/dag_evaluator:latest

      - name: Rollback if build fails
        if: failure()  # Only run if the build step failed
        run: |
          echo "Rolling back to the last successful commit..."
          # You can choose to revert your code here
          git checkout HEAD^  # This checks out the previous commit
          git push -f origin HEAD:main  # Replace 'main' with your branch name

